### PR TITLE
Bump version to 1.3.2; Add Windows support

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
I specifically removed noarch because `%PREFIX%\{bin, lib}` is not in `%PATH%` on Windows

**Comment by blink1073** [comment]
Thanks!

**Comment by blink1073** [comment]
@dfroger, mind merging this?

**Comment by nehaljwani** [comment]
Friendly bump! :sweat_smile:

**Comment by SylvainCorlay** [comment]
👍

**Comment by blink1073** [comment]
@ocefpaf, @jakirkham, mind merging this one?

**Comment by ocefpaf** [comment]
Thanks @nehaljwani for the PR and @blink1073 for the ping.

**Pull request merged**
