### PR TITLE
bump to 1.3.2, Re-rendered with conda-smithy 2.4.2

### PR DESCRIPTION
**Pull request by bollwyvl**
Here's a shiny new yarn (version `1.3.2`, released last week) with rerendered recipe!

### CODE REVIEW

**Comment by bollwyvl** [comment]
Wow, that `noarch: True` with ol' CircleCI is truly ferocious. Does the approach of updating `bin` already Just Work ™️ on windows?

**Comment by bollwyvl** [comment]
Yeah, just tried it out on win 10. The bundled `%CONDA_PREFIX%\bin\yarn.cmd` works great, but isn't on the `%PATH%`: it would be lovely to get a proper wrapper working for that...

**Comment by blink1073** [comment]
Is this blocked on a change to `conda-build`?

**Comment by dougalsutherland** [comment]
Superseded by #4. Thanks @bollwyvl / @blink1073, and sorry this stagnated. :/

**Comment by bollwyvl** [comment]
Woohooo! Feel free to maintainerize me as well!

**Pull request closed without merging**
