### PR TITLE
Update to 1.6.0

### PR DESCRIPTION
**Pull request by dhirschfeld**

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Motivated by https://github.com/jupyterlab/jupyterlab/pull/4474

**Comment by dhirschfeld** [comment]
@conda-forge/staged-recipes - ping!

**Comment by scopatz** [comment]
Hi @dhirschfeld - inside of a recipe, you should ping the maintainers, and if that fails, @conda-forge/core. Those on @conda-forge/staged-recipes don't have rights on the feedstocks, per-se.

**Comment by dhirschfeld** [comment]
Sure, can do. I got that advice from the [`README.md`](https://github.com/conda-forge/staged-recipes/blob/master/README.md#12-my-pull-request-passes-all-checks-but-hasnt-received-any-attention--how-do-i-call-attention-to-my-pr--what-is-the-customary-amount-of-time-to-wait)
> *If your PR is passing all checks, but has not been acted on by the staged recipes maintainers for 1 week, you can ping @conda-forge/staged-recipes to request action.*

**Comment by scopatz** [comment]
Ahh yeah, but that is the readme for staged-recipes

**Comment by dhirschfeld** [comment]
^^^ Valid point! :stuck_out_tongue_winking_eye:

**Comment by CJ-Wright** [comment]
Or you can ping @conda-forge/yarn for the maintainers of yarn

**Comment by dougalsutherland** [comment]
So it looks like @dfroger is the only maintainer of yarn right now, and as far as I can tell he hasn't been on github at all in months. I'm going to add myself as a maintainer to avoid that, and merge. Thanks @dhirschfeld!

**Pull request merged**
